### ISSUE TITLE
ReLIC

### ISSUE THREAD

**Issue by shixishi** [NightShade99/Self-Supervised-Vision#3]
I have a problem with line 196 of the models/relic.py file, self.save_state(epoch), but after reviewing the code, I found that the ReLIC class does not have a save_state() function.

**Comment by NightShade99** [comment]
Hi, thanks for pointing out. The function was supposed to facilitate saving training states including the model, optimizer and scheduler's state dict so one could resume training from a certain point (if it breaks). However I never needed that feature myself so I never implemented it, but forgot to remove its calls from the code. I have commented that line for now, so the rest of it should work fine. Let me know.

**Comment by shixishi** [comment]
> Hi, thanks for pointing out. The function was supposed to facilitate saving training states including the model, optimizer and scheduler's state dict so one could resume training from a certain point (if it breaks). However I never needed that feature myself so I never implemented it, but forgot to remove its calls from the code. I have commented that line for now, so the rest of it should work fine. Let me know.

Thank you for your comments！

**Comment by NightShade99** [comment]
Closing for now.
